<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Concours;

class ConcoursSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $concours = [
            ['libelle' => 'AIDE SOIGNANTE', 'statut' => 'active'],
            ['libelle' => 'ASECNA-EAMAC', 'statut' => 'active'],
            ['libelle' => 'CAFOP', 'statut' => 'active'],
            ['libelle' => 'CAP', 'statut' => 'active'],
            ['libelle' => 'CONCOURS DE RECRUTEMENT', 'statut' => 'active'],
            ['libelle' => 'Agent Technique de la Statistique', 'statut' => 'active'],
            ['libelle' => 'Animateur Culturel', 'statut' => 'active'],
            ['libelle' => 'Archiviste', 'statut' => 'active'],
            ['libelle' => 'Assistant Conservateur Archives', 'statut' => 'active'],
            ['libelle' => 'Assistant Conservateur Bibliothèque', 'statut' => 'active'],
            ['libelle' => 'Assistant Conservateur de Musée', 'statut' => 'active'],
            ['libelle' => 'Assistant Conservateur Documentation', 'statut' => 'active'],
            ['libelle' => 'Assistant des Productions Végétales et Animales – Agriculture', 'statut' => 'active'],
            ['libelle' => 'Assistant des Productions Végétales et Animales – Eaux et Forêts', 'statut' => 'active'],
            ['libelle' => 'Assistant des Productions Végétales et Animales – Elevage', 'statut' => 'active'],
            ['libelle' => 'Assistant des Productions Végétales et Animales – Halieute', 'statut' => 'active'],
            ['libelle' => 'Assistant Documentaliste', 'statut' => 'active'],
            ['libelle' => 'Assistant Social', 'statut' => 'active'],
            ['libelle' => 'Assistant Social Adjoint', 'statut' => 'active'],
            ['libelle' => 'Bibliothécaire', 'statut' => 'active'],
            ['libelle' => 'Chargé de Production', 'statut' => 'active'],
            ['libelle' => 'Chargé de Rédaction', 'statut' => 'active'],
            ['libelle' => 'Chimie  de  l\'Eau  et  de  l\'Environnement', 'statut' => 'active'],
            ['libelle' => 'Chirurgien Dentiste', 'statut' => 'active'],
            ['libelle' => 'Conseiller Adjoint d\'Action Culturelle', 'statut' => 'active'],
            ['libelle' => 'Conseiller d\'Action Culturelle', 'statut' => 'active'],
            ['libelle' => 'Conservateur Archiviste', 'statut' => 'active'],
            ['libelle' => 'Conservateur Bibliothécaire', 'statut' => 'active'],
            ['libelle' => 'Conservateur de Musée', 'statut' => 'active'],
            ['libelle' => 'Conservateur Documentaliste', 'statut' => 'active'],
            ['libelle' => 'Demographe', 'statut' => 'active'],
            ['libelle' => 'Docteur Vétérinaire', 'statut' => 'active'],
            ['libelle' => 'Infirmier Diplômé d\'Etat', 'statut' => 'active'],
            ['libelle' => 'Ingénieur Agroalimentaire', 'statut' => 'active'],
            ['libelle' => 'Ingénieur Agronome', 'statut' => 'active'],
            ['libelle' => 'Ingénieur Agronome (Défenses des cultures)', 'statut' => 'active'],
            ['libelle' => 'Ingénieur de Chimie', 'statut' => 'active'],
            ['libelle' => 'Ingénieur de Contrôle de Qualité', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Eaux et Forêts', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Mines', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Techniques Agricoles', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Techniques Agroalimentaires', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Techniques de Chimie', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Techniques de Contrôle de Qualité', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Techniques des Eaux et Forêts', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Techniques des Mines', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Techniques des Travaux Publics', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Techniques d\'Elevage', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Techniques Informatiques', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Travaux Publics', 'statut' => 'active'],
            ['libelle' => 'Ingénieur des Travaux Statistiques', 'statut' => 'active'],
            ['libelle' => 'Ingénieur du Génie Rural', 'statut' => 'active'],
            ['libelle' => 'Ingénieur du Génie Sanitaire', 'statut' => 'active'],
            ['libelle' => 'Ingénieur Génie Energétique', 'statut' => 'active'],
            ['libelle' => 'Ingénieur Génie Mécanique', 'statut' => 'active'],
            ['libelle' => 'Ingénieur Halieute', 'statut' => 'active'],
            ['libelle' => 'Ingénieur Hydraulique', 'statut' => 'active'],
            ['libelle' => 'Ingénieur Informaticien', 'statut' => 'active'],
            ['libelle' => 'Ingénieur Statisticien Economiste', 'statut' => 'active'],
            ['libelle' => 'Ingénieur Zootechnique', 'statut' => 'active'],
            ['libelle' => 'Inspecteur d\'orientation (CIERPA)', 'statut' => 'active'],
            ['libelle' => 'Journaliste', 'statut' => 'active'],
            ['libelle' => 'Médecin Généraliste', 'statut' => 'active'],
            ['libelle' => 'Médecin Interne des Hôpitaux', 'statut' => 'active'],
            ['libelle' => 'Moniteur des Productions Végétales et Animales – Agriculture', 'statut' => 'active'],
            ['libelle' => 'Moniteur des Productions Végétales et Animales – Eaux et Forêts', 'statut' => 'active'],
            ['libelle' => 'Moniteur des Productions Végétales et Animales – Elevage', 'statut' => 'active'],
            ['libelle' => 'Moniteur des Productions Végétales et Animales – Halieute', 'statut' => 'active'],
            ['libelle' => 'Pharmacien Généraliste', 'statut' => 'active'],
            ['libelle' => 'Pharmacien Interne', 'statut' => 'active'],
            ['libelle' => 'Producteur', 'statut' => 'active'],
            ['libelle' => 'Sage-Femme Diplômée d\'Etat', 'statut' => 'active'],
            ['libelle' => 'Technicien des Musées', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de Chimie', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de Contrôle de Qualité', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de la communication', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de la Santé – Assainissement', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de la Santé – Biomédical', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de la Santé – Laboratoire', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de la Santé – Manipulateur Radio', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de la Santé – Orthophoniste', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de la Santé – Préparateur et Gestion. Phacie', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de la Santé – Prothésiste Dentaire', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de l\'Hygiène industriel', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de l\'Informatique - Maintenance', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de l\'Informatique – Gestion', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur de Télécommunication', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur des T. P. – Routes et Transports', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur des Transports et Logistique', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur des Travaux Publics – Bâtiment et Urbanisme', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur des Travaux Publics – Equipement', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur des Travaux Publics – Géomètre', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur des Travaux Publics – Hydraulique', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur des Travaux Publics – Mines et Géologie', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur du commerce', 'statut' => 'active'],
            ['libelle' => 'Technicien Supérieur du Tourisme', 'statut' => 'active'],
            ['libelle' => 'Concours Directs', 'statut' => 'active'],
            ['libelle' => 'Adjoint Administratif', 'statut' => 'active'],
            ['libelle' => 'Adjoint Technique d\'Imprimerie', 'statut' => 'active'],
            ['libelle' => 'Agent d\'encadrement des douanes', 'statut' => 'active'],
            ['libelle' => 'Agent de Bureau', 'statut' => 'active'],
            ['libelle' => 'Agent de constatation des Impôts', 'statut' => 'active'],
            ['libelle' => 'Agent de Navigation de Police Maritime', 'statut' => 'active'],
            ['libelle' => 'Agent d\'encadrement des Etablissements Pénitentiaires', 'statut' => 'active'],
            ['libelle' => 'Agent d\'imprimerie', 'statut' => 'active'],
            ['libelle' => 'Agent Spécialisé des Travaux Publics (Chauffeur)', 'statut' => 'active'],
            ['libelle' => 'Agent Technique d\'Imprimerie', 'statut' => 'active'],
            ['libelle' => 'Aide Soignant', 'statut' => 'active'],
            ['libelle' => 'Assistant Comptable', 'statut' => 'active'],
            ['libelle' => 'Commis de Trésor', 'statut' => 'active'],
            ['libelle' => 'Garde de Sous-Préfecture', 'statut' => 'active'],
            ['libelle' => 'Inspecteur d\'Education surveillée', 'statut' => 'active'],
            ['libelle' => 'Maître(sse) d\'Education Permanente', 'statut' => 'active'],
            ['libelle' => 'Maître(sse) d\'Education Physique et Sportive', 'statut' => 'active'],
            ['libelle' => 'Maître(sse) d\'Education surveillée', 'statut' => 'active'],
            ['libelle' => 'Maîtresse Adjointe d\'Education Permanente', 'statut' => 'active'],
            ['libelle' => 'Secrétaire Assistant Comptable', 'statut' => 'active'],
            ['libelle' => 'Secrétaire Assistant de Direction', 'statut' => 'active'],
            ['libelle' => 'Secrétaire Comptable', 'statut' => 'active'],
            ['libelle' => 'Secrétaire de Direction', 'statut' => 'active'],
            ['libelle' => 'Secrétaire de Direction Bilingue (Français-Anglais)', 'statut' => 'active'],
            ['libelle' => 'Secrétaire Médical', 'statut' => 'active'],
            ['libelle' => 'CONCOURS PROFESSIONNELS', 'statut' => 'active'],
            ['libelle' => 'ENA', 'statut' => 'active'],
            ['libelle' => 'GENDARMERIE', 'statut' => 'active'],
            ['libelle' => 'INFAS', 'statut' => 'active'],
            ['libelle' => 'INPHB', 'statut' => 'active'],
            ['libelle' => 'IPNETP', 'statut' => 'active'],
            ['libelle' => 'POLICE', 'statut' => 'active'],
        ];

        foreach ($concours as $item) {
            Concours::updateOrCreate(['libelle' => $item['libelle']], $item);
        }
    }
}
